### ISSUE TITLE
please give more document

### ISSUE THREAD

**Issue by thaihaha** [sakibwebworm/Movie-Night#1]
I already install the Movie-Night but admin panel no show. pls update document or other for show admin panel.

**Comment by sakibwebworm** [comment]
Hi, can you provide a screenshot ?

**Comment by sakibwebworm** [comment]
I think you need to run following command "composer update"

**Comment by sakibwebworm** [comment]
After running, 'composer update', you should register yourself by visting appURL/register. Then you can visit the admin panel. In order to gain the admin access, you should add the code in registration form.

**Comment by thaihaha** [comment]
thank you. i will update again
